name: flutter_keynote
description: A Flutter package to create presentations very easy with Flutter pages.
version: 0.1.3
homepage: https://github.com/ach4m0/flutter_keynote

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.5
  provider: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
