name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Example Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: cd example
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email a.chamorro.ruiz@gmail.com
          git config --global user.name ach4m0
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/ach4m0/flutter_keynote.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f